table sales_teams
	lineageTag: 49fb18e8-9847-43b5-bd86-1646e15b382b

	column sales_agent
		dataType: string
		lineageTag: e26a5bbc-4f47-4f2f-b322-274877545c23
		summarizeBy: none
		sourceColumn: sales_agent

		annotation SummarizationSetBy = Automatic

	column manager
		dataType: string
		lineageTag: 7b1bb4d2-df7c-493b-a2c3-ff7a73a02026
		summarizeBy: none
		sourceColumn: manager

		annotation SummarizationSetBy = Automatic

	column regional_office
		dataType: string
		lineageTag: 6986dbd9-957e-4744-be7d-00753301f782
		summarizeBy: none
		sourceColumn: regional_office

		annotation SummarizationSetBy = Automatic

	partition sales_teams = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ganap\OneDrive\Documents\Siva Workspace\PBI\Maven Analytics\Sales CRM Dashboard\Data\sales_teams.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"sales_agent", type text}, {"manager", type text}, {"regional_office", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

